// Generated by CoffeeScript 1.3.3
(function() {

  window.AxleSite = (function() {
    AxleSite.prototype.details_url = "http://apiaxle.com/email_address.html";

    function AxleSite() {
      var _this = this;

      $("#details_form").submit(function() {
        _this.submit_details($("#details_form").serialize());
        return false;
      });

      $("#get_started").on("show", function(e) {
        // return straight away if we've done this before
        if ($.cookie("details-entered") === "true") {
          return e.preventDefault();
        }

        return e;
      });

      $("#get_started").on("hide", function() {
        _this.submit_details($("#details_form").serialize());
      });
    }

    AxleSite.prototype.submit_details = function(query_str) {
      var _this = this;

      $.ajax({
        dataType: "jsonp",
        url: this.details_url + "?" + query_str
      }).always(function () {
        $.cookie('details-entered', 'true', { expires: 365, path: "/" });
      });
    };

    return AxleSite;
  })();

  $(document).ready(function() {
    var axle;
    return axle = new AxleSite();
  });

}).call(this);
